import { StyleSheet, Platform, Dimensions } from "react-native";
import scale, { verticalScale } from "../../../components/src/Scale";
// Customizable Area Start
import { colors } from "../../utilities/src/Colors";

/** Shared home-feed spacing so search, featured, filters, and cards share one grid. */
const FEED_GUTTER = 16;
const FEED_SECTION_GAP = 16;
const FEED_CHIP_GAP = 8;
const FEED_CARD_GAP = 12;
const FEED_CARD_PAD = 12;
const DETAIL_HERO_HEIGHT = Math.round(Dimensions.get('window').height * 0.32);

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#08080f'
  },
  /** Top app bar on the events feed; dark redesign chrome. */
  feedHeaderBar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#08080f',
    paddingHorizontal: FEED_GUTTER,
    height: 56,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: 'rgba(255, 255, 255, 0.08)',
  },
  feedHeaderBrandRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexShrink: 1,
    paddingRight: 8,
  },
  feedHeaderLogo: {
    width: 28,
    height: 28,
    borderRadius: 8,
    backgroundColor: '#ff2d6b',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 8,
  },
  feedHeaderTitle: {
    fontWeight: '900',
    fontSize: 18,
    letterSpacing: 0.6,
    color: '#f0eeff',
    textTransform: 'uppercase',
  },
  feedHeaderLocationPill: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.06)',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(255, 255, 255, 0.08)',
    borderRadius: 16,
    paddingHorizontal: 10,
    paddingVertical: 6,
    marginLeft: 8,
    maxWidth: 140,
  },
  feedHeaderLocationText: {
    color: '#f0eeff',
    fontSize: 12,
    fontWeight: '600',
    marginLeft: 4,
    marginRight: 2,
    flexShrink: 1,
  },
  feedHeaderActions: {
    flexDirection: 'row',
    alignItems: 'center',
    marginLeft: 'auto',
  },
  feedHeaderIcon: {
    height: 22,
    width: 22,
    resizeMode: 'contain',
    tintColor: '#f0eeff',
  },
  feedHeaderMenuIcon: {
    height: 18,
    width: 18,
    resizeMode: 'contain',
    marginLeft: 10,
    tintColor: '#f0eeff',
  },
  feedHeaderBackIcon: {
    width: 12,
    height: 12,
    resizeMode: 'contain',
    tintColor: '#f0eeff',
  },
  feedHeaderAvatarWrap: {
    marginLeft: 10,
    width: 32,
    height: 32,
    borderRadius: 16,
    borderWidth: 1.5,
    borderColor: '#ff2d6b',
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#1a1a2e',
  },
  feedHeaderAvatar: {
    width: 32,
    height: 32,
    borderRadius: 16,
  },
  /** Groups category filters and sort/state controls under the redesign search. */
  feedToolbarSurface: {
    marginHorizontal: 0,
    backgroundColor: '#08080f',
    borderWidth: 0,
    overflow: 'visible',
    paddingBottom: 0,
  },
  /** Aligns with feedToolbarSurface so list body shares the same side rails. */
  feedListContent: {
    backgroundColor: '#08080f',
    flexGrow: 1,
  },
  /** Centered spinner in the feed body while the shows API is in flight (empty list). */
  feedListLoadingEmpty: {
    flexGrow: 1,
    minHeight: 320,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#08080f',
    paddingVertical: 40,
  },
  input: {
    flex: 1,
    height: 44,
    fontSize: 14,
    marginLeft: 8,
    color: '#f0eeff',
    paddingVertical: 0,
  },
  inputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 16,
    paddingVertical: 4,
    paddingLeft: 12,
    paddingRight: 6,
    marginHorizontal: FEED_GUTTER,
    marginTop: 12,
    marginBottom: FEED_SECTION_GAP,
    backgroundColor: '#1a1a2e',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(255, 255, 255, 0.08)',
  },
  nearMeButton: {
    backgroundColor: 'rgba(255, 45, 107, 0.15)',
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 8,
    marginLeft: 6,
  },
  nearMeButtonText: {
    color: '#ff2d6b',
    fontSize: 12,
    fontWeight: '600',
  },
  featuredCard: {
    marginHorizontal: FEED_GUTTER,
    marginBottom: FEED_SECTION_GAP,
    borderRadius: 18,
    overflow: 'hidden',
    backgroundColor: '#111120',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(255, 255, 255, 0.08)',
    height: 190,
  },
  featuredImage: {
    width: '100%',
    height: '100%',
  },
  featuredImagePlaceholder: {
    width: '100%',
    height: '100%',
    backgroundColor: '#1a1a2e',
    alignItems: 'center',
    justifyContent: 'center',
  },
  featuredOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(8, 8, 15, 0.12)',
  },
  featuredBottomFade: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    height: 72,
    backgroundColor: 'rgba(8, 8, 15, 0.38)',
  },
  featuredBadge: {
    position: 'absolute',
    top: FEED_CARD_PAD,
    left: FEED_CARD_PAD,
    backgroundColor: '#ff2d6b',
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  featuredBadgeText: {
    color: '#FFFFFF',
    fontSize: 9,
    fontWeight: '700',
    letterSpacing: 0.6,
  },
  featuredContentRow: {
    position: 'absolute',
    left: FEED_CARD_PAD,
    right: FEED_CARD_PAD,
    bottom: FEED_CARD_PAD,
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
  },
  featuredTextBlock: {
    flex: 1,
    paddingRight: 12,
  },
  featuredTitle: {
    color: '#f0eeff',
    fontSize: 22,
    fontWeight: '900',
    letterSpacing: 0.4,
    textTransform: 'uppercase',
  },
  featuredMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 4,
    flexWrap: 'wrap',
  },
  featuredMetaText: {
    color: 'rgba(240, 238, 255, 0.85)',
    fontSize: 12,
    fontWeight: '500',
    marginLeft: 4,
  },
  featuredTimeText: {
    color: '#00d4ff',
    fontSize: 12,
    fontWeight: '700',
  },
  featuredTicketButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#ff2d6b',
    alignItems: 'center',
    justifyContent: 'center',
    ...Platform.select({
      ios: {
        shadowColor: '#ff2d6b',
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 0.7,
        shadowRadius: 10,
      },
      android: {
        elevation: 6,
      },
    }),
  },
  button: {
    borderRadius: 10,
    alignItems: 'center',
  },
  verticalSeperator: {
    height: 20,
    width: 1,
    backgroundColor: '#909090',
    marginLeft: 30,
  },
  centeredView: {
    flex: 1,
    justifyContent: 'flex-end',
  },
  modalView: {
    height: '40%',
    justifyContent: 'space-between',
    backgroundColor: 'white',
    borderTopEndRadius: 20,
    padding: 35,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  textStyle: {
    color: 'white',
    fontWeight: 'bold',
    textAlign: 'center',
  },
  detailContainer: {
    backgroundColor: "#1a1a1a",
    margin: scale(25),
    borderRadius: 10,
    padding: scale(20),
  },
  detailProfileContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  detailProfileContent: {
    flexDirection: "row",
    justifyContent: "space-around",
  },
  detailProfileImageContent: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: "#878787",
  },
  detailProfileImage: {
    width: "100%",
    height: "100%",
    borderRadius: 30,
  },
  detailProfileTitleContent: {
    marginLeft: scale(10),
  },
  detailProfileTitle: {
    fontSize: 14,
    color: "#fff",
  },
  detailProfileEventTypeContent: {
    justifyContent: "center",
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "stretch",
    backgroundColor: "#70ff73",
    paddingHorizontal: 5,
    paddingVertical: 3,
    borderRadius: 6,
    marginTop: scale(10),
  },
  detailProfileEventTypeImage: {
    width: 15,
    height: 15,
    marginRight: scale(6),
  },
  detailProfileEventTypeText: {
    fontSize: 12,
    color: "#000",
    fontWeight: "500",
    marginTop: Platform.OS === "ios" ? scale(4) : 0,
  },
  detailProfileUpcomingTitle: {
    fontSize: 14,
    color: "#fff",
    marginLeft: 15,
  },
  detailProfileDateTimeContent: {
    padding: 20,
    justifyContent: "center",
    alignItems: "center",
  },
  detailProfileDateTimeHeaderContent: {
    flexDirection: "row",
    justifyContent: "space-between",
    width: "60%",
  },
  detailProfileDateTimeHeaderTime: {
    fontSize: 14,
    color: "#fff",
    textAlign: "right",
  },
  detailProfileDateTimeHeaderDate: {
    fontSize: 14,
    color: "#fff",
  },
  detailProfileDateTimeValueContent: {
    flexDirection: "row",
    justifyContent: "space-between",
    width: "75%",
    marginTop: scale(10),
  },
  detailProfileDateTimeValue: {
    fontSize: 16,
    color: "#fff",
    fontWeight: "bold",
  },
  detailProfileDetailsContainer: {
    padding: 15,
  },
  detailProfileDetailsContent: {
    marginTop: scale(8),
    flexDirection: "row",
    alignItems: "center",
  },
  detailProfileDetailsTitle: {
    fontSize: 16,
    color: "#fff",
    fontWeight: "bold",
  },
  detailProfileDetailsDesc: {
    fontSize: 16,
    color: "#fff",
    opacity: 0.6,
  },
  editImage: {
    width: scale(18),
    height: scale(18),
    marginTop: verticalScale(2),
  },
  dateBanner: {
    position: 'absolute',
    top: 20,
    right: 20,
    paddingVertical: 7,
    paddingHorizontal: 15,
    borderRadius: 10,
    backgroundColor: '#4949EE',
    flexWrap: 'wrap',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
  },
  eventDetails: {
    flexDirection: 'row',
    flex: 0.4,
    alignItems: 'center'
  },
  detailIcons: {
    width: 15,
    height: 15,
    resizeMode: 'contain'
  },
  boldText: {
    fontWeight: '700',
    fontSize: 14,
    color: '#334155',
  },
  loadingContainer: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: '#ffffffdd',
    alignItems: "center",
    justifyContent: "center",
  },
  textInput: {
    alignSelf: 'flex-end',
    paddingHorizontal: 10,
    color: colors(false).text,
    height: 50,
  },
  selector: {
    height: 50,
    justifyContent: "center",
    paddingHorizontal: 0,
  },
  downArrow: {
    width: 15,
    height:15,
    marginLeft: 10,
    marginBottom:15,
    backgroundColor: "#F1F5F9",
    transform: [{ rotate: "-90deg" }],
    resizeMode: "contain",
  },
  sortByRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    marginTop: 10,
    width: '100%',
  },
  sortByCell: {
    flex: 1,
    minWidth: 100,
  },
  sortByCellFirst: {
    flex: 1.4,
    minWidth: 120,
    marginRight: 8,
  },
  sortByCellLast: {
    flex: 1,
    minWidth: 90,
  },
  sortByTouchable: {
    flexDirection: 'row',
    alignItems: 'center',
    height: 40,
    paddingRight: 10,
    paddingLeft: 10,
    justifyContent: 'flex-start',
    minWidth: 0,
    alignSelf: 'flex-start',
  },
  sortByLabel: {
    flexShrink: 1,
    minWidth: 0,
    fontSize: 14,
  },
  sortByLabelText: {
    marginRight: 5,
  },
  sortByContainerAndroid: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 8,
    height: 40,
    minWidth: 0,
    alignSelf: 'flex-start',
    position: 'relative',
  },
  sortByAndroidLabelRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingRight: 10,
  },
  sortByLabelAndroid: {
    fontSize: 14,
    minWidth: 0,
  },
  downArrowAndroid: {
    width: 8,
    marginLeft: 4,
    backgroundColor: '#F1F5F9',
    transform: [{ rotate: '-90deg' }],
    resizeMode: 'contain',
  },
  sortByPickerOverlay: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: 'center',
  },
  sortByPickerInvisible: {
    height: 40,
    width: '100%',
    opacity: 0,
  },
  sortByPickerWrap: {
    flex: 1,
    minWidth: 80,
    // backgroundColor:"red",
    height:100
  },
  sortByPicker: {
    flex: 1,
    height: 40,
    marginLeft: -4,
  },
  txt: {
    fontFamily: "OpenSans",
    alignSelf: "flex-start",
    color: colors(false).text,
    fontWeight:"600"
  },
  welcomeToPopupText: {
    textAlign: 'center',
    fontSize: 20,
    lineHeight: 28,
    marginTop: 10,
    color: "#334166",
  },
  localShowsPopupText: {
    fontWeight: '700',
    fontSize: 28,
    lineHeight: 32,
    bottom: '5%',
    textAlign: 'center',
    color: '#3333CC',
  },
  loginFirstPopupText: {
    textAlign: 'center',
    lineHeight: 24,
    marginBottom: '5%',
    fontWeight: '400',
    fontSize: 16,
    color: '#334166',
  },
  createAccountPopupText: {
    color: '#3333CC',
    fontWeight: '700',
    lineHeight: 24,
    marginBottom: '4%',
    fontSize: 16,
    textAlign: 'center',
  },
  loginBtnPopupText: {
    backgroundColor: '#3333CC',
    borderRadius: 8,
    height: 56,
    justifyContent: 'center',
  },
  loginTxtPopupText: {
    color: 'white',
    fontWeight: 'bold',
    textAlign: 'center',
    fontSize: 16,
  },
  headerContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: "white",
    height: 50,
  },
  headerIconBtn : {
    flexDirection: "row",
    alignItems: 'center',
    width: 40,
    height: 40
},
  backButton: {
    width: 20,
  },
  arrowIcon: {
    width: 12,
    left: 0,
    resizeMode: "contain",
  },
  headerText: {
    fontWeight: "700",
    fontSize: 24,
    color: "#0F172A",
    textAlign: "center",
    textAlignVertical:'center',
    maxWidth:'70%'
  },
  hamburgerButton: {
    
  },
  hamburgerIcon: {
    height: 20,
    width: 20,
    resizeMode: "contain",
  
  },
  image: {
    width: '100%',
    height: 270,
    borderRadius: 10,
    marginBottom: 10,
  },
  threeDotsButton: {
    position: 'absolute',
    right: 10,
    top: 10,
    padding: 10,
  },
  threeDotsIcon: {
    width: 30,
    height: 30,
    resizeMode: 'contain',
  },
  divider: {
    height: "50%",
    width: 1,
    backgroundColor: "#CBD5E1",
    alignSelf: 'center',
  },
  gallery: {
    height: 40,
    width: 40,
    resizeMode: 'contain',
    tintColor: '#00000050',
  },
  menuContainer: {
    position: 'absolute',
    right: 20,
    top: 60,
    backgroundColor: '#FFFFFF',
    borderRadius: 10,
    padding: 10,
    paddingLeft: 30,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.9,
    shadowRadius: 3,
    elevation: 3,
  },
  menuButton: {
    paddingHorizontal: 15,
    paddingVertical: 10,
  },
  menuButtonText: {
    fontSize: 16,
    fontWeight: '400',
    color: '#0F172A',
    textAlignVertical: 'center',
  },
  commentsParentView: {
    backgroundColor: '#33415580',
  },
  commentsView: {
    height: '75%',
    padding: 20,
    justifyContent: 'flex-start',
  },
  commentsHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center'
  },
  commentsHeadingText: {
    fontSize: 24,
    fontWeight: 'bold',
  },
  horizontalRuler: {
    width: '100%',
    height: 1,
    backgroundColor: '#E2E8F0',
    marginVertical: 15,
  },
  commentsListContainer: {
    flex: 1,
  },
  emojiSelectionBar: {
    height: 40,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  emojiSelectionBarIcon: {
    fontSize: 20,
  },
  commentInputArea: {
    height: 50,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center'
  },
  userAvatar: {
    width: 40,
    height: 40,
    borderRadius: 75,
  },
  userAvatarContainer: {
    backgroundColor: "#FCFCFF",
    width: 42,
    height: 42,
    borderRadius: 80,
    alignSelf: "center",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: '#C5C5FF',
    marginRight: 10,
  },
  commentTextInput: {
    flex: 1,
    borderWidth: 1,
    borderColor: "#C5C5FF",
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingRight: 50,
    paddingTop: 12,
    height: '100%',
    fontSize: 16,
    textAlignVertical: 'center'
  },
  emojiButton: {
    position: 'absolute',
    right: 10,
    height: 30,
    width: 30,
  },
  emojiIcon: {
    width: 30,
    height: 30,
    resizeMode: 'contain',
  },
  noCommentsContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 16,
  },
  startConversationText: {
    marginTop: 5,
  },
  commentItem: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginVertical: 10,
  },
  commentContent: {
    flex: 1
  },
  commenterName: {
    fontSize: 16,
    fontWeight: "bold",
  },
  commentText: {
    fontSize: 14
  },
  likeContainer: {
    alignSelf: "flex-start",
    alignItems: "center",
    justifyContent: "center",
  },
  likesCountText: {
    color: "#94A3B8",
    textAlign: "center",
  },
  replyButton: {
    alignSelf: "flex-start",
  },
  replyButtonText: {
    fontWeight: "bold",
    fontSize: 14,
    color: "#94A3B8",
  },
  showReplyButton: {
    flexDirection: "row",
    alignSelf: "flex-start",
    alignItems: "center",
  },
  horizontalBar: {
    height: 1,
    width: 20,
    marginRight: 10,
    backgroundColor: "#94A3B8",
  },
  showReplyButtonText: {
    fontSize: 14,
    color: "#94A3B8"
  },
  replyText: {
    marginTop: 10,
  },
  rowBack: {
    alignItems: 'center',
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginVertical: 10,
  },
  rowFront: {
    alignItems: 'center',
    backgroundColor: '#FFF',
    width: '100%',
    flexDirection: "row",
    justifyContent: "space-between",
    marginVertical: 10,
    paddingRight: 5,
  },
  backRightBtn: {
    alignItems: 'center',
    bottom: 0,
    justifyContent: 'center',
    position: 'absolute',
    top: 0,
    width: 60,
  },
  backRightBtnLeft: {
    backgroundColor: '#33415580',
    right: 60,
  },
  backRightBtnRight: {
    backgroundColor: '#DC2626',
    right: 0,
  },
  redDot: {
    height: 8,
    width: 8,
    borderRadius: 5,
    backgroundColor: "red",
    position: "absolute",
    right: -4,
    top: 2,
  },
  notificationWrapper: {
    position: 'relative',
    justifyContent: 'center',
    alignItems: 'center',
  },
  notificationBadge: {
    position: 'absolute',
    top: -6,
    right: -8,
    minWidth: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: '#F04438',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 4,
  },
  notificationBadgeText: {
    color: '#FFFFFF',
    fontSize: 10,
    fontWeight: '700',
  },
  disablePopupIconContainer: {
    position: "absolute",
    right: 20,
    top: 20,
  },
  textDeleteHeading: {
    fontWeight: "700",
    fontSize: 26,
    lineHeight: 28,
    marginBottom: 10,
    marginTop: 25,
    color: "#0F172A",
  },
  textDelete: {
    fontSize: 18,
  },
  deleteButtonContainer: {
    backgroundColor: "#3333CC",
    width: "100%",
    padding: 15,
    borderRadius: 10,
    marginTop: 15,
  },
  textDeleteButton: {
    color: colors(false).white,
    fontWeight: "700",
    fontSize: 18,
    alignSelf: "center",
  },
  keepButtonContainer: {
    backgroundColor: "transparent",
  },
  textKeepButton: {
    color: "#3333CC",
  },
  filterButton: {
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 9,
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    backgroundColor: '#1a1a2e',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
    marginRight: 8,
  },
  filterButtonActive: {
    backgroundColor: '#ff2d6b',
    borderColor: '#ff2d6b',
  },
  filterButtonText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#8880aa',
  },
  filterButtonTextActive: {
    color: '#FFFFFF',
  },
  filterPillsRow: {
    paddingLeft: FEED_GUTTER,
    paddingRight: 0,
    marginBottom: FEED_CHIP_GAP,
  },
  filterPillsRowLast: {
    paddingLeft: FEED_GUTTER,
    paddingRight: 0,
    marginBottom: 0,
  },
  filterPillsContent: {
    paddingRight: FEED_GUTTER,
  },
  sortPill: {
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 8,
    backgroundColor: '#1a1a2e',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
    marginRight: 8,
  },
  sortPillActive: {
    backgroundColor: 'rgba(255, 45, 107, 0.15)',
    borderColor: '#ff2d6b',
  },
  sortPillText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#8880aa',
  },
  sortPillTextActive: {
    color: '#ff2d6b',
  },
  reportModalContent: {
    height: 'auto',
    maxHeight: '85%',
    width: '90%',
    alignSelf: 'center',
    padding: 24,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    borderBottomLeftRadius: 20,
    borderBottomRightRadius: 20,
  },
  reportHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  reportTitle: {
    fontWeight: '700',
    fontSize: 20,
    color: '#0F172A',
  },
  reportSubtitle: {
    marginTop: 16,
    fontSize: 14,
    color: '#64748B',
    fontWeight: '500',
  },
  reportReasonsContainer: {
    marginTop: 12,
  },
  reportReasonButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 12,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    marginBottom: 10,
    backgroundColor: '#FFFFFF',
  },
  reportReasonButtonSelected: {
    borderColor: '#4949EE',
    backgroundColor: '#EEF2FF',
  },
  reportRadioOuter: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 1.5,
    borderColor: '#CBD5E1',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  reportRadioOuterSelected: {
    borderColor: '#4949EE',
  },
  reportRadioInner: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: '#4949EE',
  },
  reportReasonText: {
    fontSize: 14,
    color: '#0F172A',
    flex: 1,
  },
  reportReasonTextSelected: {
    color: '#1E1B4B',
    fontWeight: '600',
  },
  reportErrorText: {
    color: '#DC2626',
    fontSize: 12,
    marginTop: 4,
  },
  reportCommentInput: {
    marginTop: 12,
    borderWidth: 1,
    borderColor: '#C5C5FF',
    borderRadius: 10,
    padding: 12,
    minHeight: 100,
    textAlignVertical: 'top',
    color: '#0F172A',
  },
  reportActions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    marginTop: 20,
  },
  reportButton: {
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 8,
  },
  reportCancelButton: {
    backgroundColor: '#E2E8F0',
    marginRight: 12,
  },
  reportCancelText: {
    color: '#0F172A',
    fontWeight: '600',
  },
  reportSubmitButton: {
    backgroundColor: '#3333CC',
  },
  reportSubmitText: {
    color: '#FFFFFF',
    fontWeight: '700',
  },
  closeBtn:{
    padding:8,
    position: 'absolute',
    top: 20,
    right: 20,
    width: 20,
    height: 20,
    justifyContent: 'center',
    alignItems: 'center'
  },
  showsCountRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginHorizontal: FEED_GUTTER,
    marginTop: FEED_SECTION_GAP,
    marginBottom: FEED_SECTION_GAP,
  },
  showsCountLabelWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    marginRight: 10,
  },
  showsCountDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#ff2d6b',
    marginRight: 6,
  },
  showsCountText: {
    color: '#ff2d6b',
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 0.8,
  },
  showsCountLine: {
    flex: 1,
    height: StyleSheet.hairlineWidth,
    backgroundColor: 'rgba(255, 255, 255, 0.12)',
    marginRight: 10,
  },
  showsCountArea: {
    color: '#8880aa',
    fontSize: 12,
    fontWeight: '600',
  },
  compactShowCard: {
    flexDirection: 'column',
    marginHorizontal: FEED_GUTTER,
    marginBottom: FEED_CARD_GAP,
    padding: FEED_CARD_PAD,
    borderRadius: 16,
    backgroundColor: '#111120',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(255, 255, 255, 0.08)',
  },
  compactShowMainRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  compactShowThumbWrap: {
    width: 108,
    height: 108,
    borderRadius: 14,
    overflow: 'hidden',
    backgroundColor: '#1a1a2e',
  },
  compactShowThumb: {
    width: 108,
    height: 108,
  },
  compactShowThumbPlaceholder: {
    width: 108,
    height: 108,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#1a1a2e',
  },
  compactShowBody: {
    flex: 1,
    marginLeft: FEED_CARD_PAD,
    minWidth: 0,
    minHeight: 108,
  },
  compactShowTitleRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
  },
  compactShowTitle: {
    flex: 1,
    color: '#f0eeff',
    fontSize: 16,
    fontWeight: '800',
    letterSpacing: 0.2,
    textTransform: 'uppercase',
    paddingRight: 8,
  },
  compactShowGenre: {
    color: '#8880aa',
    fontSize: 12,
    fontWeight: '500',
    marginTop: 2,
  },
  compactShowLineup: {
    color: '#c8c2e6',
    fontSize: 11,
    fontWeight: '500',
    marginTop: 2,
  },
  compactShowMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    marginTop: 8,
  },
  compactShowVenue: {
    color: '#f0eeff',
    fontSize: 12,
    fontWeight: '600',
    marginLeft: 4,
    flexShrink: 1,
  },
  compactShowTime: {
    color: '#ffe138',
    fontSize: 12,
    fontWeight: '700',
    marginLeft: 8,
  },
  compactShowActions: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 8,
  },
  compactShowActionIcons: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  compactShowActionIcon: {
    height: 18,
    width: 18,
    resizeMode: 'contain',
    tintColor: '#8880aa',
    marginRight: 10,
  },
  compactShowLikeIcon: {
    height: 18,
    width: 20,
    resizeMode: 'contain',
    tintColor: '#ff2d6b',
  },
  compactShowCalendarText: {
    color: '#ff2d6b',
    fontWeight: '500',
    fontSize: 12,
  },
  compactShowSocialText: {
    color: '#8880aa',
    fontSize: 12,
    fontWeight: '600',
    marginTop: 6,
  },
  compactShowSocialLink: {
    color: '#ff2d6b',
    fontWeight: '400',
  },
  compactSeeMoreText: {
    fontWeight: '400',
    fontSize: 14,
    textDecorationLine: 'underline',
    paddingHorizontal: FEED_GUTTER,
    paddingTop: 4,
    paddingBottom: FEED_CARD_GAP,
    color: '#ff2d6b',
    textAlign: 'right',
  },
  compactShowFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: FEED_CARD_PAD,
    paddingTop: FEED_CARD_PAD,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: 'rgba(255, 255, 255, 0.1)',
  },
  compactShowCategoryPill: {
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 6,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(255, 77, 120, 0.38)',
    backgroundColor: '#32151d',
  },
  compactShowCategoryText: {
    color: '#ff4d78',
    fontSize: 13,
    fontWeight: '800',
    letterSpacing: 0.2,
  },
  compactShowFooterDate: {
    color: '#c4bdd6',
    fontSize: 12,
    fontWeight: '500',
  },

  /** AllEventDetailScreen — dark redesign */
  detailScreen: {
    flex: 1,
    width: '100%',
    height: '100%',
    backgroundColor: '#08080f',
  },
  detailListContent: {
    backgroundColor: '#08080f',
    flexGrow: 1,
    paddingBottom: 36,
  },
  detailLoadingContainer: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: '#08080f',
    alignItems: 'center',
    justifyContent: 'center',
  },
  detailOverlayHeaderWrap: {
    height: 0,
    overflow: 'hidden',
  },
  detailOverlayHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingTop: 8,
    height: 56,
  },
  detailCircleBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: 'rgba(0, 0, 0, 0.45)',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(255, 255, 255, 0.22)',
  },
  detailHeaderRight: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  detailCircleBtnGap: {
    marginLeft: 8,
  },
  detailHeroWrap: {
    width: '100%',
    height: DETAIL_HERO_HEIGHT,
    marginBottom: 12,
    backgroundColor: '#08080f',
    overflow: 'hidden',
  },
  detailHeroImage: {
    width: '100%',
    height: '100%',
  },
  detailHeroPlaceholder: {
    width: '100%',
    height: '100%',
    backgroundColor: '#1a1a2e',
    justifyContent: 'center',
    alignItems: 'center',
  },
  detailHeroScrim: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(8, 8, 15, 0.08)',
  },
  detailHeroFadeWrap: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    height: 150,
  },
  detailHeroFadeLayer: {
    position: 'absolute',
    left: 0,
    right: 0,
    backgroundColor: '#08080f',
  },
  detailHeroTopBar: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    zIndex: 20,
  },
  detailHeroTopBarInner: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingTop: 8,
  },
  detailHeroActions: {
    position: 'absolute',
    top: 0,
    right: 16,
    zIndex: 12,
  },
  detailHeroMeta: {
    position: 'absolute',
    left: 16,
    right: 16,
    bottom: 16,
  },
  detailHotBadge: {
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#ff2d6b',
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 5,
    marginBottom: 8,
  },
  detailHotBadgeText: {
    color: '#FFFFFF',
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 1,
    marginLeft: 4,
  },
  detailHeroTitle: {
    color: '#FFFFFF',
    fontSize: 26,
    lineHeight: 30,
    fontWeight: '900',
    letterSpacing: 0.5,
    textTransform: 'uppercase',
    marginBottom: 8,
  },
  detailStateCaption: {
    color: '#c4bdd6',
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
    marginBottom: 6,
  },
  detailHeroMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
  },
  detailGenrePill: {
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 6,
    borderWidth: 1,
    borderColor: '#ff2d6b',
    backgroundColor: 'rgba(255, 45, 107, 0.12)',
    marginRight: 10,
    marginBottom: 4,
  },
  detailGenrePillText: {
    color: '#ff2d6b',
    fontSize: 13,
    fontWeight: '700',
  },
  detailPriceText: {
    color: '#ff2d6b',
    fontSize: 20,
    fontWeight: '800',
    marginBottom: 4,
  },
  detailBadgeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 8,
  },
  detailStatusBadge: {
    width: 87,
    height: 28,
    borderRadius: 5,
    marginRight: 10,
  },
  detailSoldOutBadge: {
    width: 75,
    height: 28,
    borderRadius: 5,
  },
  detailSection: {
    paddingHorizontal: 16,
  },
  detailStatsBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#1a1a2e',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(196, 189, 214, 0.28)',
    paddingHorizontal: 18,
    paddingVertical: 12,
    minHeight: 48,
    marginBottom: 16,
  },
  detailStatItem: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  detailStatCount: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '700',
    marginLeft: 8,
  },
  detailStatSpacer: {
    flex: 1,
  },
  detailInfoCardsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 22,
  },
  detailInfoCard: {
    flex: 1,
    backgroundColor: '#111120',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(196, 189, 214, 0.28)',
    paddingHorizontal: 12,
    paddingVertical: 14,
    marginHorizontal: 4,
  },
  detailInfoCardFirst: {
    marginLeft: 0,
  },
  detailInfoCardLast: {
    marginRight: 0,
  },
  detailInfoCardLabel: {
    color: '#8880aa',
    fontSize: 12,
    fontWeight: '600',
    marginTop: 8,
    marginBottom: 4,
  },
  detailInfoCardValue: {
    color: '#f0eeff',
    fontSize: 15,
    fontWeight: '800',
  },
  detailSectionLabel: {
    color: '#8880aa',
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 1.2,
    marginBottom: 10,
  },
  detailLineupRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#111120',
    borderRadius: 14,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(255, 255, 255, 0.08)',
    paddingHorizontal: 12,
    paddingVertical: 12,
    marginBottom: 8,
  },
  detailLineupIndex: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
    backgroundColor: '#1a1a2e',
  },
  detailLineupIndexActive: {
    backgroundColor: '#ff2d6b',
  },
  detailLineupIndexText: {
    color: '#c4bdd6',
    fontSize: 13,
    fontWeight: '800',
  },
  detailLineupIndexTextActive: {
    color: '#FFFFFF',
  },
  detailLineupName: {
    color: '#f0eeff',
    fontSize: 15,
    fontWeight: '700',
    flex: 1,
  },
  detailAboutText: {
    color: '#c4bdd6',
    fontSize: 14,
    lineHeight: 22,
    fontWeight: '400',
    marginBottom: 22,
  },
  detailVenueCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#111120',
    borderRadius: 16,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(255, 255, 255, 0.08)',
    padding: 14,
    marginBottom: 10,
  },
  detailVenueIconWrap: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: '#1a1a2e',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  detailVenueTextWrap: {
    flex: 1,
    paddingRight: 8,
  },
  detailVenueName: {
    color: '#f0eeff',
    fontSize: 16,
    fontWeight: '800',
    marginBottom: 4,
  },
  detailVenueAddress: {
    color: '#8880aa',
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '400',
  },
  detailRulesHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#111120',
    borderRadius: 16,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(255, 255, 255, 0.08)',
    paddingHorizontal: 14,
    paddingVertical: 16,
  },
  detailRulesHeaderOpen: {
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
    borderBottomWidth: 0,
  },
  detailRulesHeaderText: {
    color: '#f0eeff',
    fontSize: 15,
    fontWeight: '700',
    flex: 1,
    paddingRight: 8,
  },
  detailRulesBody: {
    backgroundColor: '#111120',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(255, 255, 255, 0.08)',
    borderTopWidth: 0,
    borderBottomLeftRadius: 16,
    borderBottomRightRadius: 16,
    paddingHorizontal: 14,
    paddingBottom: 14,
    marginBottom: 8,
  },
  detailRuleRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginTop: 12,
  },
  detailRuleIcon: {
    marginRight: 10,
    marginTop: 1,
  },
  detailRuleTitle: {
    color: '#f0eeff',
    fontSize: 14,
    fontWeight: '700',
    marginBottom: 2,
  },
  detailRuleText: {
    color: '#c4bdd6',
    fontSize: 13,
    lineHeight: 20,
    fontWeight: '400',
    flex: 1,
  },
  detailMoreShowsRow: {
    paddingLeft: 16,
    marginBottom: 14,
  },
  detailMoreShowCard: {
    width: 148,
    height: 112,
    borderRadius: 16,
    overflow: 'hidden',
    marginRight: 10,
    backgroundColor: '#111120',
  },
  detailMoreShowImage: {
    width: '100%',
    height: '100%',
  },
  detailMoreShowFade: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    height: 64,
    backgroundColor: 'rgba(8, 8, 15, 0.7)',
  },
  detailMoreShowMeta: {
    position: 'absolute',
    left: 10,
    right: 10,
    bottom: 10,
  },
  detailMoreShowTitle: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '800',
    textTransform: 'uppercase',
    marginBottom: 2,
  },
  detailMoreShowDate: {
    color: '#ffe138',
    fontSize: 11,
    fontWeight: '700',
  },
  detailVenueProfileBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#ff2d6b',
    paddingVertical: 14,
    marginBottom: 16,
  },
  detailVenueProfileBtnText: {
    color: '#ff2d6b',
    fontSize: 15,
    fontWeight: '800',
    marginLeft: 8,
  },
  detailTicketsWrap: {
    marginTop: 8,
    marginBottom: 12,
  },
  detailPrimaryBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#ff2d6b',
    borderRadius: 16,
    paddingVertical: 16,
    width: '100%',
    shadowColor: '#ff2d6b',
    shadowOpacity: 0.35,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 6,
  },
  detailPrimaryBtnText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '800',
    letterSpacing: 0.6,
    marginLeft: 8,
  },
  detailSecondaryBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'transparent',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.12)',
    paddingVertical: 14,
    width: '100%',
    marginTop: 12,
  },
  detailSecondaryBtnText: {
    color: '#f0eeff',
    fontSize: 15,
    fontWeight: '700',
  },
  detailWebsiteRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    backgroundColor: '#111120',
    borderRadius: 16,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(255, 255, 255, 0.08)',
    paddingHorizontal: 14,
    paddingVertical: 14,
    marginBottom: 10,
  },
  detailMetaLabel: {
    color: '#8880aa',
    fontSize: 13,
    fontWeight: '700',
    marginRight: 8,
  },
  detailMetaValue: {
    color: '#ff2d6b',
    fontSize: 14,
    fontWeight: '600',
    flex: 1,
  },
  detailShowTypeWrap: {
    marginBottom: 10,
  },
  detailFeatureRow: {
    flexDirection: 'row',
    width: '43%',
    marginRight: 10,
    marginBottom: 8,
    alignItems: 'flex-start',
  },
  detailFeatureText: {
    color: '#c4bdd6',
    fontSize: 14,
    lineHeight: 22,
    fontWeight: '400',
    flex: 1,
  },
  detailErrorTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#f0eeff',
    textAlign: 'center',
    marginBottom: 8,
  },
  detailErrorBody: {
    fontSize: 14,
    color: '#8880aa',
    textAlign: 'center',
    marginBottom: 24,
  },
  detailRetryBtn: {
    backgroundColor: '#ff2d6b',
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 12,
    marginBottom: 12,
  },
  detailRetryText: {
    color: '#FFFFFF',
    fontWeight: '700',
  },
  detailGoBackText: {
    color: '#ff2d6b',
    fontWeight: '700',
  },
  detailMenuContainer: {
    position: 'absolute',
    right: 16,
    top: 110,
    backgroundColor: '#111120',
    borderRadius: 12,
    padding: 8,
    minWidth: 220,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(255, 255, 255, 0.08)',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.4,
    shadowRadius: 8,
    elevation: 6,
    zIndex: 40,
  },
  detailMenuButtonText: {
    fontSize: 15,
    fontWeight: '500',
    color: '#f0eeff',
    textAlignVertical: 'center',
  },
});

// Customizable Area End
